### PR TITLE
mpich 4.1.1

### PR DESCRIPTION
**Pull request by skupr-anaconda**
Changelog: https://github.com/pmodels/mpich/blob/v4.1.1/CHANGES
License: https://github.com/pmodels/mpich/blob/v4.1.1/COPYRIGHT
Requirements:
- https://github.com/pmodels/mpich/tree/v4.1.1
- https://github.com/pmodels/mpich/blob/v4.1.1/autogen.sh
- https://github.com/pmodels/mpich/blob/v4.1.1/configure.ac

Actions:
1. Fix perl locale settings on `osx`. In logs, there were warnings (not errors) on `osx` but the build failed anyway
2. Add `-fplt` flag for `ppc64le` (following the conda-forge recipe)
3. Enable `-fallow-argument-mismatch` flag for all platforms (see c-f recipe)
4. Remove `MACOSX_DEPLOYMENT_TARGET` because it fails
5. Add two new patches for `osx` (following the conda-forge recipe)
6. Add `missing_dso_whitelist` for `s390x` (a known issue for this platform)
7. Add `patch` and `perl` to `build`. Perl is required https://github.com/pmodels/mpich/blob/27df1e04b291dae3d664174f6dfe949c5b83c6e3/README.vin#L51
8.  Add '_openmp_mutex' to `run` on `linux` because `lib/libmpifort.so.12.3.0` requires it
9. Fix home, dev & doc urls
10. Update `license` name
11. Skip lints

### CODE REVIEW

**Review by varlackc — COMMENTED** [review]
We might need to remove the `abs.yaml` file once the package is ready to merge.

**Review by danpetry — APPROVED** [review]

**Review by cbouss — COMMENTED** [review]
Overall it looks good, but can you add a comment on why are you disabling error-overlinking?

**Comment by skupr-anaconda** [comment]
I want to notice that this `mpich` bumping to the major version won't break downstream packages because all they have hard runtime pinnings:
```
anaconda | 2022.10 | mpich 3.3.2 external_0
anaconda | 2022.05 | mpich 3.3.2 hc856adb_0
anaconda | 2021.11 | mpich 3.3.2 hc856adb_0
daal4py | 2021.6.0 | mpich >=3.3.2,<3.4.0a0
daal4py | 2021.5.0 | mpich >=3.3.2,<3.4.0a0
daal4py | 2021.4.0 | mpich >=3.3.2,<3.4.0a0
daal4py | 2021.3.0 | mpich >=3.3.2,<3.4.0a0
daal4py | 2021.2.2 | mpich >=3.3.2,<3.4.0a0
mpi4py | 3.1.4 | mpich >=3.3,<3.4.0a0
mpi4py | 3.0.3 | mpich >=3.3,<3.4.0a0
mpich-mpicc | 3.3.2 | mpich 3.3.2 hc856adb_0
mpich-mpicc | 3.2.1 | mpich 3.2.1 hf39692e_8
mpich-mpicxx | 3.3.2 | mpich 3.3.2 hc856adb_0
mpich-mpicxx | 3.2.1 | mpich 3.2.1 hf39692e_8
mpich-mpifort | 3.3.2 | mpich 3.3.2 hc856adb_0
mpich-mpifort | 3.2.1 | mpich 3.2.1 hf39692e_8
ptscotch | 6.0.9 | mpich >=3.3.2,<3.4.0a0

```

**Comment by skupr-anaconda** [comment]
@cbouss I disabled `error-overlinking` because of:
`["  ERROR (mpich,lib/libmpifort.so.12.3.0): .. but ['_openmp_mutex'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)"]`
I've added a comment to abs.yaml

**Comment by skupr-anaconda** [comment]
> We might need to remove the `abs.yaml` file once the package is ready to merge.

I've removed it

**Comment by skupr-anaconda** [comment]
Added `_openmp_mutex  # [linux]` to `run` and remove `abs.yaml`

**Review by cbouss — APPROVED** [review]
LGTM

**Pull request merged**
